services:
  - type: web
    name: crypto-predictor-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000  # Optional; Render will assign one if not set
